<?php 
 return [ 
 	'product_lock_delay' => '15', 
 	'customer_role_id' => '1', 
 	'token_expires_in' => '15', 
 	'refresh_token_expires_in' => '30', 
 	'personal_access_token_expires_in' => '6', 
 	'imported_by' => '1', 
 	'in_cdn_for_media' => '0', 
 	'product_import_endpoint' => 'https://search.shajgoj.com/wp-json/wc/v2/products', 
 	'sku_is_required' => '1', 
 	'sku_default_multiplier' => '1', 
 	'pg_min_qty' => '1', 
 	'pg_discount_amount' => '0', 
 	'pg_variation_types' => [ 
 		'shade',
 		'size',
 	],
 	'delivery_fee' => '45', 
 	'frontend_url' => 'http://localhost:8000/api/products/', 
 	'pagination' => '25', 
 	'ngrok_url' => 'https://d07f-202-83-126-26.ngrok.io/', 
 	'shop_url' => 'http://134.209.109.139', 
 	'token_expire_time' => '90', 
 	'send_static_otp' => '1', 
 	'sitemap' => [ 
 		'https://shop.shajgoj.com/product-category/makeup/',
 		'https://shop.shajgoj.com/product-category/skin/',
 		'https://shop.shajgoj.com/product-category/offers/',
 		'https://shop.shajgoj.com/product-category/men/',
 		'https://shop.shajgoj.com/product-category/skin/shop-by-concern-1-skin/',
 		'https://shop.shajgoj.com/brand/mamaearth/',
 		'https://shop.shajgoj.com/product-category/makeup/',
 	],
 	'twitter_domain' => 'shop.shajgoj.com', 
];